name: maven-cache
description: Caches Maven artifacts

runs:
  using: composite
  steps:
    - name: Cache Maven packages
      uses: actions/cache@v4.3.0
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        path: ~/.m2/repository
