/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ClusterConnectionSettingsAuthenticationMethod = typeof ClusterConnectionSettingsAuthenticationMethod[keyof typeof ClusterConnectionSettingsAuthenticationMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterConnectionSettingsAuthenticationMethod = {
  NO_AUTH: 'NO_AUTH',
} as const;
