/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ClusterInfo {
  clusterId?: string;
  internalName?: string;
  /** @minLength 1 */
  displayName: string;
  /** @minLength 1 */
  icon: string;
  /**
   * @minLength 1
   * @pattern ^#([A-Fa-f0-9]{6})$
   */
  color: string;
}
