/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterInfo } from './ClusterInfo';
import type { ClusterConnectionSettings } from './ClusterConnectionSettings';

export interface ClusterCreation {
  clusterInfo?: ClusterInfo;
  clientConnectionSettings?: ClusterConnectionSettings;
  adminConnectionSettings?: ClusterConnectionSettings;
}
