/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterConnectionSettingsAuthenticationMethod } from './ClusterConnectionSettingsAuthenticationMethod';

export interface ClusterConnectionSettings {
  id?: number;
  /** @minLength 1 */
  serviceUrl: string;
  authenticationMethod: ClusterConnectionSettingsAuthenticationMethod;
  authenticationDetails?: string;
}
