name: build-interfero
description: Builds and publishes Interfero Image

inputs:
  docker-hub-username:
    description: Docker Hub username
    required: true
  docker-hub-token:
    description: Docker Hub access token
    required: true

runs:
  using: composite
  steps:
    - id: setup-java
      name: Setup Java
      uses: ./.github/actions/java-setup

    - id: maven-cache
      name: Maven Cache
      uses: ./.github/actions/maven-cache

    - id: run-unit-tests
      name: Run Unit Tests
      uses: ./.github/actions/unit-tests

    - id: run-integration-tests
      name: Run Integration Tests
      uses: ./.github/actions/integration-tests

    - id: verify-tag
      name: Verify Tag
      uses: ./.github/actions/verify-tag

    - id: build-jar
      name: Build JAR
      shell: bash
      run: mvn clean package --batch-mode -Pproduction -DskipTests

    - id: save-documentation
      name: Save Documentation
      uses: ./.github/actions/save-documentation

    - id: setup-docker-buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: docker-login
      name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-hub-username }}
        password: ${{ inputs.docker-hub-token }}

    - id: docker-build-and-push-pre-release
      name: Build and Push Docker Image (pre-release)
      if: steps.verify-tag.outputs.IS_PROD_RELEASE == 'false'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: dennisschaefer/interfero:${{ steps.verify-tag.outputs.TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - id: docker-build-and-push-prod-release
      name: Build and Push Docker Image (prod-release)
      if: steps.verify-tag.outputs.IS_PROD_RELEASE == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          dennisschaefer/interfero:${{ steps.verify-tag.outputs.TAG }}
          dennisschaefer/interfero:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max