name: java-setup
description: Sets up Java environment

inputs: 
  distribution:
    description: Java distribution
    default: corretto
  java-version:
    description: Java version
    default: '25'

runs:
  using: composite
  steps:
    - id: setup-java
      name: Setup Java ${{ inputs.java-version }} with distribution ${{ inputs.distribution }}
      uses: actions/setup-java@v5.0.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
