package io.interfero.clusters.repositories;

import io.interfero.clusters.domain.ClusterConnectionSettingsEntity;

import java.util.Optional;
import java.util.Set;

public interface ClusterConnectionSettingsRepository
{
    /**
     * Returns all cluster connections settings from the data store.
     * @return A set of all cluster connections
     */
    Set<ClusterConnectionSettingsEntity> findAll();

    /**
     * Returns the settings for a cluster connection by its ID.
     * @param id The unique identifier of the connection settings
     * @return An Optional containing the cluster connection settings if found, or empty if not found
     */
    Optional<ClusterConnectionSettingsEntity> findById(Long id);

    /**
     * Saves the settings for a cluster connection to the data store. The ID of the cluster will be generated by the
     * data store if not provided.
     * @param clusterConnectionSettings The cluster connection settings to save
     * @return The saved cluster connection settings
     */
    ClusterConnectionSettingsEntity save(ClusterConnectionSettingsEntity clusterConnectionSettings);

    /**
     * Deletes the settings for a cluster connection by its ID.
     * @param id The unique identifier of the connection settings
     */
    void deleteById(Long id);

    /**
     * Deletes all cluster connections settings from the data store.
     */
    void deleteAll();
}
