/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClusterCreation,
  ClusterInfo
} from '../schemas';

import { axiosInstance } from '../axios-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getAllClusterInfo = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ClusterInfo[]>(
      {url: `/api/clusters`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAllClusterInfoQueryKey = () => {
    return [
    `/api/clusters`
    ] as const;
    }

    
export const getGetAllClusterInfoQueryOptions = <TData = Awaited<ReturnType<typeof getAllClusterInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllClusterInfo>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllClusterInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllClusterInfo>>> = ({ signal }) => getAllClusterInfo(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllClusterInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllClusterInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getAllClusterInfo>>>
export type GetAllClusterInfoQueryError = unknown


export function useGetAllClusterInfo<TData = Awaited<ReturnType<typeof getAllClusterInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllClusterInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllClusterInfo>>,
          TError,
          Awaited<ReturnType<typeof getAllClusterInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllClusterInfo<TData = Awaited<ReturnType<typeof getAllClusterInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllClusterInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllClusterInfo>>,
          TError,
          Awaited<ReturnType<typeof getAllClusterInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllClusterInfo<TData = Awaited<ReturnType<typeof getAllClusterInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllClusterInfo>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllClusterInfo<TData = Awaited<ReturnType<typeof getAllClusterInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllClusterInfo>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllClusterInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createCluster = (
    clusterCreation: ClusterCreation,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ClusterCreation>(
      {url: `/api/clusters`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: clusterCreation, signal
    },
      options);
    }
  


export const getCreateClusterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCluster>>, TError,{data: ClusterCreation}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCluster>>, TError,{data: ClusterCreation}, TContext> => {

const mutationKey = ['createCluster'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCluster>>, {data: ClusterCreation}> = (props) => {
          const {data} = props ?? {};

          return  createCluster(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateClusterMutationResult = NonNullable<Awaited<ReturnType<typeof createCluster>>>
    export type CreateClusterMutationBody = ClusterCreation
    export type CreateClusterMutationError = unknown

    export const useCreateCluster = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCluster>>, TError,{data: ClusterCreation}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCluster>>,
        TError,
        {data: ClusterCreation},
        TContext
      > => {

      const mutationOptions = getCreateClusterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getClusterInfoById = (
    clusterId: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ClusterInfo>(
      {url: `/api/clusters/${clusterId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetClusterInfoByIdQueryKey = (clusterId?: string,) => {
    return [
    `/api/clusters/${clusterId}`
    ] as const;
    }

    
export const getGetClusterInfoByIdQueryOptions = <TData = Awaited<ReturnType<typeof getClusterInfoById>>, TError = unknown>(clusterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterInfoById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClusterInfoByIdQueryKey(clusterId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClusterInfoById>>> = ({ signal }) => getClusterInfoById(clusterId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(clusterId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClusterInfoById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClusterInfoByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getClusterInfoById>>>
export type GetClusterInfoByIdQueryError = unknown


export function useGetClusterInfoById<TData = Awaited<ReturnType<typeof getClusterInfoById>>, TError = unknown>(
 clusterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterInfoById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClusterInfoById>>,
          TError,
          Awaited<ReturnType<typeof getClusterInfoById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClusterInfoById<TData = Awaited<ReturnType<typeof getClusterInfoById>>, TError = unknown>(
 clusterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterInfoById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClusterInfoById>>,
          TError,
          Awaited<ReturnType<typeof getClusterInfoById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClusterInfoById<TData = Awaited<ReturnType<typeof getClusterInfoById>>, TError = unknown>(
 clusterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterInfoById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetClusterInfoById<TData = Awaited<ReturnType<typeof getClusterInfoById>>, TError = unknown>(
 clusterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterInfoById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClusterInfoByIdQueryOptions(clusterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




