name: integration-tests
description: Run Integration-Tests

inputs:
  database-vendor:
    description: Database vendor to use for integration tests (Testcontainers)
    required: false
    default: postgres
  postgres-version:
    description: Postgres version to use for integration tests (Testcontainers)
    required: false
    default: "17.0"
  timescaledb-version:
    description: TimescaleDB version to use for integration tests (Testcontainers)
    required: false
    default: "2.23.1-pg17"

runs:
  using: composite
  steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v6

    - id: setup-java
      name: Setup Java
      uses: ./.github/actions/java-setup

    - id: maven-cache
      name: Maven Cache
      uses: ./.github/actions/maven-cache

    - id: setup-environment-variables
      name: Setup Environment Variables
      shell: bash
      run: |
        echo "INTERFERO_DATABASE_VENDOR=${{ inputs.database-vendor }}" >> .testcontainers.env
        echo "INTERFERO_POSTGRES_VERSION=${{ inputs.postgres-version }}" >> .testcontainers.env
        echo "INTERFERO_TIMESCALEDB_VERSION=${{ inputs.timescaledb-version }}" >> .testcontainers.env
        cat .testcontainers.env

    - id: run-integration-tests
      name: Run Integration-Tests
      shell: bash
      run: mvn test --batch-mode -Dtest=*IT