name: integration-tests
description: Run Integration-Tests

runs:
  using: composite
  steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v6

    - id: setup-java
      name: Setup Java
      uses: ./.github/actions/java-setup

    - id: maven-cache
      name: Maven Cache
      uses: ./.github/actions/maven-cache

    - id: run-integration-tests
      name: Run Integration-Tests
      shell: bash
      run: mvn test --batch-mode -Dtest=*IT